//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnicaBitsion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
        public int idCliente { get; set; }
        [Required(ErrorMessage = "Introduzca un nombre!")]
        [StringLength(50, ErrorMessage = "Su nombre debe ser de al menos de 10 caracteres y no superar los 50.", MinimumLength = 10)]
        [RegularExpression(@"[a-zA-Z ]{2,254}", ErrorMessage = "No se permiten caracteres especiales ;)")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "Seleccione una fecha de nacimiento.")]
        public System.DateTime nacimiento { get; set; }
        [Required(ErrorMessage = "Seleccione un género!")]
        public int idGenero { get; set; }
        public bool estado { get; set; }
        public bool maneja { get; set; }
        public bool lentes { get; set; }
        public bool diabetico { get; set; }
        public string enfermedades { get; set; }
        [Range(1000000, 99999999)]
        public int dni { get; set; }
    
        public virtual Generos Generos { get; set; }
    }
}
